[general]
log_level = 3

[scene]
clearColor = [0.2, 0.2, 0.2, 1.0]  # RGBA
showGrid = true

[render.graphics]
backend = "directx12"
max_framerate = 0
vsync = true
buffer_count = 3

[render.lighting]
ambient_light_intensity = 0.7
sun_light_intensity = 0.9
ambient_color = [1.0, 1.0, 1.0]  # RGB
sun_light_color = [1.0, 1.0, 1.0]  # RGB
sun_light_direction = [0.0, 0.0, -1.0]

[window]
backend = "win32"
title = "Reveal3D"
resolution = [1920, 1080]

[camera]
movement_speed = 5.0
fov = 90.0
near_plane = 0.01
far_plane = 100.0
sensitivity = 0.05
